version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: solar-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: solar

  app:
    build: .
    container_name: solar-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/solar
    volumes:
      - .:/usr/src/app
volumes:
  mongo_data:
