version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: solar-mongo
    volumes:
      - mongo_db:/data/db

    environment:
       MONGO_INITDB_DB: solar



  app:
    build: .
    container_name: solar-app
    ports:
      - "3000:3000"

    environment:
      MONGO_URI: mongodb://mongo:27017/solar

    volumes:
      - .:/usr/src/app

    depends_on:
      - mongo

    



volumes:
   mongo_db: